import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService {
  static final ValueNotifier<String> languageNotifier = ValueNotifier<String>('vi');

  static final Map<String, Map<String, String>> _translations = {
    'vi': {
      // General
      'app_name': 'Đếm ngược Kỷ niệm',
      'cancel': 'Hủy',
      'save': 'Lưu',
      'delete': 'Xóa',
      'ok': 'OK',
      'error': 'Lỗi',
      'success': 'Thành công',
      'yes': 'Có',
      'no': 'Không',
      
      // Home Screen
      'timer_settings': 'Cài đặt đếm ngược',
      'enter_seconds': 'Nhập số giây (tối đa 60)',
      'start': 'Bắt đầu',
      'screenshot_saved': 'Đã lưu ảnh vào thư viện',
      'screenshot_error': 'Lỗi khi lưu ảnh:',
      'capturing': 'Đang chụp...',
      'capture_screen': 'Chụp màn hình',
      'upcoming': 'Sắp tới',
      'no_events_yet': 'Chưa có kỷ niệm nào',
      'tap_plus_to_add': 'Bấm dấu + để thêm sự kiện đầu tiên',
      'add_event': 'Thêm kỷ niệm',
      'no_upcoming_events': 'Không có sự kiện sắp tới',
      'all_events_passed': 'Các sự kiện của bạn đều đã qua.',
      'view_all_events': 'Xem tất cả',
      'all_events': 'Tất cả Kỷ niệm',
      'days': 'Ngày',
      'hours': 'Giờ',
      'minutes': 'Phút',
      'seconds': 'Giây',
      'exit_app_title': 'Thoát ứng dụng',
      'exit_app_desc': 'Bạn có chắc chắn muốn thoát khỏi ứng dụng Đếm ngược Kỷ niệm không?',
      'exit': 'Thoát',
      'delete_event_title': 'Xóa kỷ niệm?',
      'delete_event_desc': 'Bạn có chắc muốn xóa "{title}" không?',
      'home': 'Trang chủ',
      'events': 'Sự kiện',
      'gifts': 'Quà tặng',
      'settings': 'Cài đặt',
      'passed': 'Đã qua',
      
      // Settings Screen
      'language': 'Ngôn ngữ',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'language_changed_vi': 'Đã đổi ngôn ngữ sang Tiếng Việt',
      'language_changed_en': 'Changed language to English',
      'premium_account': 'Tài khoản Premium',
      'premium_member': 'Thành viên VIP Premium',
      'upgrade_premium': 'Nâng cấp Premium \$2.00',
      'premium_unlocked_desc': 'Đã sở hữu trọn bộ đặc quyền vĩnh viễn',
      'premium_locked_desc': 'Ẩn quảng cáo, mở khóa tất cả hiệu ứng nền',
      'enter_gift_code': 'Nhập gift code',
      'enter_gift_code_desc': 'Nhập mã quà tặng VIP hoặc Gift Code đặc biệt',
      'test_premium': 'Bật/Tắt Premium (Chế độ Test)',
      'test_premium_desc': 'Chỉ dùng thử nghiệm: Tự do bật tắt để kiểm tra giao diện & quảng cáo',
      'notifications': 'Thông báo',
      'event_reminders': 'Nhắc nhở sự kiện',
      'event_reminders_desc': 'Nhận thông báo khi sắp đến ngày kỷ niệm',
      'reminder_time': 'Thời điểm nhắc',
      'reminder_time_desc_7': 'Trước 1 tuần',
      'reminder_time_desc_days': 'Trước {days} ngày',
      'notification_hour': 'Giờ gửi thông báo',
      'notification_sound': 'Âm thanh thông báo',
      'notification_sound_desc': 'Phát âm thanh khi có thông báo',
      'ui_and_lang': 'Giao diện & Ngôn ngữ',
      'customize_ui': 'Tùy chỉnh Giao diện',
      'customize_ui_desc': 'Đổi hiệu ứng nền và font chữ',
      'info': 'Thông tin',
      'rate_app': 'Đánh giá ứng dụng',
      'rate_app_desc': 'Để lại nhận xét trên Store',
      'version': 'Phiên bản',
      'test_notification_btn': 'Thử nghiệm thông báo (5s)',
      'test_notification_msg': 'Sẽ hiển thị thông báo sau 5 giây!',
      'thank_you_rating': 'Cảm ơn bạn đã đánh giá!',
      'gift_code_title': 'Nhập Gift Code',
      'gift_code_instruction': 'Nhập mã quà tặng VIP để mở khóa Premium hoặc Gift Code để mở hiệu ứng đặc biệt:',
      'activate': 'Kích hoạt',
      
      // Detail Screen
      'event_detail': 'Chi tiết Kỷ niệm',
      'edit': 'Sửa',
      'days_passed': 'ngày đã qua',
      'days_remaining': 'ngày nữa',
      'today': 'Hôm nay!',
      'congratulations': 'Chúc mừng!',
      'send_wish': 'Gửi lời chúc',
      'find_gifts': 'Tìm quà tặng',
      
      // Add Event Screen
      'add_new_event': 'Thêm Kỷ niệm mới',
      'edit_event': 'Sửa Kỷ niệm',
      'event_name': 'Tên sự kiện',
      'event_name_hint': 'VD: Kỷ niệm ngày cưới, Sinh nhật...',
      'event_date': 'Ngày kỷ niệm',
      'select_date': 'Chọn ngày',
      'event_icon': 'Biểu tượng',
      'event_color': 'Màu sắc',
      'name_empty_error': 'Vui lòng nhập tên sự kiện',
      
      // Gifts Screen
      'discover_gifts': 'Khám phá Quà tặng',
      'premium_gifts_locked': 'Quà tặng Premium bị khóa',
      'unlock_premium_gifts': 'Nâng cấp Premium để mở khóa tất cả quà tặng độc quyền',
      'unlock_now': 'Mở khóa ngay',
      
      // Premium Dialog
      'premium_features': 'Đặc quyền Premium',
      'no_ads': 'Không quảng cáo',
      'unlock_all_effects': 'Mở khóa mọi hiệu ứng nền',
      'buy_premium': 'Mua Premium - \$2.00',
      'restore_purchase': 'Khôi phục giao dịch',
      
      // Widgets
      'background_effect': 'Hiệu ứng nền',
      'font_style': 'Font chữ',
      'none': 'Không có',
      'select_bg_image': 'Chọn ảnh nền',
      'remove_bg_image': 'Xóa ảnh nền',
      'event_pinned': '📌 Đã ghim sự kiện lên thanh thông báo!',
      'repeat_yearly': 'Lặp lại hàng năm',
      'use_lunar_calendar': 'Tính theo Âm lịch',
      'rename_event': 'Đổi tên sự kiện',
      'select_category': 'Chọn danh mục',
      'select_color': 'Chọn màu sắc',
      'select_date_warning': 'Vui lòng chọn ngày!',
      'select_vn': '🇻🇳 Chọn Việt Nam',
      'select_intl': '🌍 Chọn Quốc tế',
      'deselect_all': '✕ Bỏ chọn tất cả',
      'enter_sender_receiver': 'Vui lòng nhập tên người gửi và người nhận',
      'wish_copied': 'Đã copy lời chúc!',
      'your_name': 'Tên bạn (xưng)',
      'receiver_name': 'Tên người nhận',
      'anniversary_occasion': 'Dịp kỷ niệm',
      'copy': 'Copy',
      'premium_effect_unlocked': '🎉 Đã mở khóa vĩnh viễn hiệu ứng {effect}!',
      'effect_prefix': 'Hiệu ứng {effect}',
      // Home Screen - additional
      'nearest': 'Gần nhất',
      'yearly': '↺ hàng năm',
      'lunar_date': '(Ngày {day} tháng {month} Âm lịch)',
      'gift_suggestions': 'Gợi ý quà',
      'view_detail': 'Xem chi tiết',
      'view_fullscreen': 'Xem Toàn Màn Hình',
      'fullscreen_ad_desc': 'Xem 1 đoạn video quảng cáo ngắn hoặc Nâng cấp Premium để thưởng thức chế độ toàn màn hình tuyệt đẹp!',
      'upgrade_premium_price': 'Nâng cấp Premium (\\\$2.00)',
      'watch_ad_free': 'Xem Quảng Cáo (Miễn phí)',
      'watch_fullscreen': 'Xem toàn màn hình',
      'all_events_tab': 'Tất cả sự kiện',
      'empty_state_desc': 'Hãy thêm những ngày quan trọng\ncủa bạn để không bao giờ quên!',
      'add_now': '+ Thêm ngay',
      'no_upcoming_desc': 'Tất cả sự kiện đã diễn ra.\nThêm sự kiện mới hoặc xem tab Tất cả.',
      'view_all_events_arrow': 'Xem tất cả sự kiện →',

      // Detail Screen - additional
      'today_is_anniversary': '🎊 Hôm nay là ngày kỷ niệm!',
      'days_ago': '✓ Đã diễn ra {days} ngày trước',
      'days_left': '⏳ Còn {days} ngày nữa',
      'countdown_label': 'ĐẾM NGƯỢC',
      'position_in_year': 'Vị trí trong năm {year}',
      'jan_1': '1 tháng 1',
      'dec_31': '31 tháng 12',
      'category': 'Danh mục',
      'original_date': 'Ngày gốc',
      'next_occurrence': 'Lần kế tiếp',
      'gift_suggestions_detail': 'Gợi ý quà tặng',
      'find_meaningful_gift': 'Tìm món quà ý nghĩa nhất',
      'custom_icon': 'Biểu tượng tùy chỉnh',
      'custom_icon_ad_desc': 'Xem 1 đoạn video quảng cáo ngắn hoặc Nâng cấp Premium để sử dụng biểu tượng tuyệt đẹp nhé!',
      'congrats_desc': 'Chúc bạn một ngày thật ý nghĩa và tràn đầy niềm vui.',

      // Add Event Screen - additional
      'custom_icon_add_desc': 'Xem 1 đoạn video quảng cáo ngắn hoặc Nâng cấp Premium để lưu lại thay đổi biểu tượng tuyệt đẹp nhé!',
      'add_anniversary': 'Thêm Kỷ niệm',
      'anniversary_name': 'Tên kỷ niệm',
      'anniversary_name_hint': 'VD: Sinh nhật vợ yêu...',
      'please_enter_name': 'Vui lòng nhập tên',
      'event_category': 'Danh mục sự kiện',
      'need_ad_for_icon': '💡 Cần xem quảng cáo để thay đổi biểu tượng',
      'notes': 'Ghi chú (tùy chọn)',
      'notes_hint': 'Thêm ghi chú cho kỷ niệm này...',
      'select_date_hint': 'Chọn ngày...',
      'change_icon': 'Thay đổi biểu tượng',
      'auto_update_yearly': 'Tự động cập nhật sang năm tiếp theo',
      'for_traditional_holidays': 'Dành cho ngày lễ truyền thống',
      'save_anniversary': 'Lưu Kỷ niệm ✨',
      'select_from_presets': 'Chọn từ ngày lễ có sẵn',
      'popular_holidays': 'Ngày lễ phổ biến',
      'vietnam': 'Việt Nam',
      'international': 'Quốc tế',
      'all_holidays': 'Tất cả ngày lễ',
      'selected_count': 'Đã chọn: {count}',
      'add_count_days': 'Thêm {count} ngày',
      'lunar_date_display': '{day}/{month} (Âm lịch)',
      'added': 'Đã thêm',
      // Countdown Card
      'card_yearly': '↺ năm',
      'card_gift': '🛍️ Quà',
      'card_today': '🎊 Hôm nay!',
      'card_days_left': '⏳ Còn {days} ngày',
      'card_tomorrow': '⏳ Ngày mai',
      'card_days_passed': '✓ Đã qua {days} ngày',
      // Event Categories
      'cat_love': 'Tình yêu',
      'cat_wedding': 'Cưới xin',
      'cat_birthday': 'Sinh nhật',
      'cat_family': 'Gia đình',
      'cat_festival': 'Lễ hội',
      'cat_education': 'Học tập',
      'cat_gratitude': 'Tri ân',
      'cat_achievement': 'Thành tựu',
      'cat_national': 'Quốc gia',
      'cat_profession': 'Nghề nghiệp',
      'cat_awareness': 'Nhận thức',
      'cat_other': 'Khác',
    },
    'en': {
      // General
      'app_name': 'Anniversary Countdown',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'ok': 'OK',
      'error': 'Error',
      'success': 'Success',
      'yes': 'Yes',
      'no': 'No',
      
      // Home Screen
      'timer_settings': 'Timer Settings',
      'enter_seconds': 'Enter seconds (max 60)',
      'start': 'Start',
      'screenshot_saved': 'Screenshot saved to gallery',
      'screenshot_error': 'Error saving screenshot:',
      'capturing': 'Capturing...',
      'capture_screen': 'Take Screenshot',
      'upcoming': 'Upcoming',
      'no_events_yet': 'No events yet',
      'tap_plus_to_add': 'Tap + to add your first event',
      'add_event': 'Add Event',
      'no_upcoming_events': 'No upcoming events',
      'all_events_passed': 'All your events have passed.',
      'view_all_events': 'View All',
      'all_events': 'All Events',
      'days': 'Days',
      'hours': 'Hours',
      'minutes': 'Minutes',
      'seconds': 'Seconds',
      'exit_app_title': 'Exit App',
      'exit_app_desc': 'Are you sure you want to exit the app?',
      'exit': 'Exit',
      'delete_event_title': 'Delete Event?',
      'delete_event_desc': 'Are you sure you want to delete "{title}"?',
      'home': 'Home',
      'events': 'Events',
      'gifts': 'Gifts',
      'settings': 'Settings',
      'passed': 'Passed',
      
      // Settings Screen
      'language': 'Language',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'language_changed_vi': 'Đã đổi ngôn ngữ sang Tiếng Việt',
      'language_changed_en': 'Changed language to English',
      'premium_account': 'Premium Account',
      'premium_member': 'Premium VIP Member',
      'upgrade_premium': 'Upgrade Premium \$2.00',
      'premium_unlocked_desc': 'Permanently unlocked all exclusive features',
      'premium_locked_desc': 'Hide ads, unlock all background effects',
      'enter_gift_code': 'Enter gift code',
      'enter_gift_code_desc': 'Enter VIP gift code or special effect code',
      'test_premium': 'Toggle Premium (Test Mode)',
      'test_premium_desc': 'For testing only: freely toggle to test UI & ads',
      'notifications': 'Notifications',
      'event_reminders': 'Event Reminders',
      'event_reminders_desc': 'Get notified when an event is approaching',
      'reminder_time': 'Reminder Time',
      'reminder_time_desc_7': '1 week before',
      'reminder_time_desc_days': '{days} days before',
      'notification_hour': 'Notification Time',
      'notification_sound': 'Notification Sound',
      'notification_sound_desc': 'Play sound when receiving notification',
      'ui_and_lang': 'UI & Language',
      'customize_ui': 'Customize UI',
      'customize_ui_desc': 'Change background effect and font',
      'info': 'Info',
      'rate_app': 'Rate App',
      'rate_app_desc': 'Leave a review on the Store',
      'version': 'Version',
      'test_notification_btn': 'Test Notification (5s)',
      'test_notification_msg': 'Notification will show in 5 seconds!',
      'thank_you_rating': 'Thank you for your rating!',
      'gift_code_title': 'Enter Gift Code',
      'gift_code_instruction': 'Enter a VIP code to unlock Premium or a Gift Code to unlock special effects:',
      'activate': 'Activate',
      
      // Detail Screen
      'event_detail': 'Event Details',
      'edit': 'Edit',
      'days_passed': 'days passed',
      'days_remaining': 'days to go',
      'today': 'Today!',
      'congratulations': 'Congratulations!',
      'send_wish': 'Send Wish',
      'find_gifts': 'Find Gifts',
      
      // Add Event Screen
      'add_new_event': 'Add New Event',
      'edit_event': 'Edit Event',
      'event_name': 'Event Name',
      'event_name_hint': 'Ex: Wedding Anniversary, Birthday...',
      'event_date': 'Event Date',
      'select_date': 'Select Date',
      'event_icon': 'Icon',
      'event_color': 'Color',
      'name_empty_error': 'Please enter an event name',
      
      // Gifts Screen
      'discover_gifts': 'Discover Gifts',
      'premium_gifts_locked': 'Premium Gifts Locked',
      'unlock_premium_gifts': 'Upgrade to Premium to unlock all exclusive gifts',
      'unlock_now': 'Unlock Now',
      
      // Premium Dialog
      'premium_features': 'Premium Features',
      'no_ads': 'No Ads',
      'unlock_all_effects': 'Unlock All Background Effects',
      'buy_premium': 'Buy Premium - \$2.00',
      'restore_purchase': 'Restore Purchase',
      
      // Widgets
      'background_effect': 'Background Effect',
      'font_style': 'Font Style',
      'none': 'None',
      'select_bg_image': 'Select Background Image',
      'remove_bg_image': 'Remove Background Image',
      'event_pinned': '📌 Event pinned to notification bar!',
      'repeat_yearly': 'Repeat Yearly',
      'use_lunar_calendar': 'Use Lunar Calendar',
      'rename_event': 'Rename Event',
      'select_category': 'Select Category',
      'select_color': 'Select Color',
      'select_date_warning': 'Please select a date!',
      'select_vn': '🇻🇳 Select Vietnam',
      'select_intl': '🌍 Select International',
      'deselect_all': '✕ Deselect All',
      'enter_sender_receiver': 'Please enter sender and receiver names',
      'wish_copied': 'Wish copied!',
      'your_name': 'Your Name',
      'receiver_name': 'Receiver Name',
      'anniversary_occasion': 'Anniversary Occasion',
      'copy': 'Copy',
      'premium_effect_unlocked': '🎉 Permanently unlocked {effect} effect!',
      'effect_prefix': '{effect} Effect',
      // Home Screen - additional
      'nearest': 'Nearest',
      'yearly': '↺ yearly',
      'lunar_date': '(Day {day} Month {month} Lunar)',
      'gift_suggestions': 'Gift Ideas',
      'view_detail': 'View Detail',
      'view_fullscreen': 'View Fullscreen',
      'fullscreen_ad_desc': 'Watch a short ad or Upgrade Premium to enjoy the beautiful fullscreen mode!',
      'upgrade_premium_price': 'Upgrade Premium (\\\$2.00)',
      'watch_ad_free': 'Watch Ad (Free)',
      'watch_fullscreen': 'View fullscreen',
      'all_events_tab': 'All Events',
      'empty_state_desc': 'Add your important dates\nso you never forget!',
      'add_now': '+ Add Now',
      'no_upcoming_desc': 'All events have passed.\nAdd a new event or view All tab.',
      'view_all_events_arrow': 'View all events →',

      // Detail Screen - additional
      'today_is_anniversary': '🎊 Today is the anniversary!',
      'days_ago': '✓ Happened {days} days ago',
      'days_left': '⏳ {days} days to go',
      'countdown_label': 'COUNTDOWN',
      'position_in_year': 'Position in {year}',
      'jan_1': 'Jan 1',
      'dec_31': 'Dec 31',
      'category': 'Category',
      'original_date': 'Original Date',
      'next_occurrence': 'Next Occurrence',
      'gift_suggestions_detail': 'Gift Suggestions',
      'find_meaningful_gift': 'Find the most meaningful gift',
      'custom_icon': 'Custom Icon',
      'custom_icon_ad_desc': 'Watch a short ad or Upgrade Premium to use beautiful icons!',
      'congrats_desc': 'Wishing you a meaningful and joyful day.',

      // Add Event Screen - additional
      'custom_icon_add_desc': 'Watch a short ad or Upgrade Premium to save beautiful icon changes!',
      'add_anniversary': 'Add Anniversary',
      'anniversary_name': 'Anniversary Name',
      'anniversary_name_hint': "e.g.: Wife's Birthday...",
      'please_enter_name': 'Please enter a name',
      'event_category': 'Event Category',
      'need_ad_for_icon': '💡 Need to watch an ad to change icon',
      'notes': 'Notes (optional)',
      'notes_hint': 'Add notes for this anniversary...',
      'select_date_hint': 'Select date...',
      'change_icon': 'Change Icon',
      'auto_update_yearly': 'Automatically update to next year',
      'for_traditional_holidays': 'For traditional holidays',
      'save_anniversary': 'Save Anniversary ✨',
      'select_from_presets': 'Select from preset holidays',
      'popular_holidays': 'Popular Holidays',
      'vietnam': 'Vietnam',
      'international': 'International',
      'all_holidays': 'All Holidays',
      'selected_count': 'Selected: {count}',
      'add_count_days': 'Add {count} days',
      'lunar_date_display': '{day}/{month} (Lunar)',
      'added': 'Added',
      // Countdown Card
      'card_yearly': '↺ yearly',
      'card_gift': '🛍️ Gift',
      'card_today': '🎊 Today!',
      'card_days_left': '⏳ {days} days left',
      'card_tomorrow': '⏳ Tomorrow',
      'card_days_passed': '✓ Passed {days} days',
      // Event Categories
      'cat_love': 'Love',
      'cat_wedding': 'Wedding',
      'cat_birthday': 'Birthday',
      'cat_family': 'Family',
      'cat_festival': 'Festival',
      'cat_education': 'Education',
      'cat_gratitude': 'Gratitude',
      'cat_achievement': 'Achievement',
      'cat_national': 'National',
      'cat_profession': 'Profession',
      'cat_awareness': 'Awareness',
      'cat_other': 'Other',
    }
  };

  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    languageNotifier.value = prefs.getString('language') ?? 'vi';
  }

  static Future<void> changeLanguage(String lang) async {
    languageNotifier.value = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', lang);
  }

  static String translate(String key, {Map<String, String>? params}) {
    String text = _translations[languageNotifier.value]?[key] ?? key;
    if (params != null) {
      params.forEach((paramKey, paramValue) {
        text = text.replaceAll('{$paramKey}', paramValue);
      });
    }
    return text;
  }
}

// Global shortcut for translation
String t(String key, {Map<String, String>? params}) => LocalizationService.translate(key, params: params);
